version: '3.9'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: best-crm-frontend:latest
    env_file:
      - .env
    networks:
      traefik:
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.crm-front.rule=Host(`${DOMAIN}`)"
      - "traefik.http.services.crm-front.loadbalancer.server.port=8080"
      - 'traefik.http.routers.crm-front.entrypoints=http,https'
      - 'traefik.http.routers.crm-front.tls=true'
      - "traefik.http.routers.crm-front.tls.certresolver=letsEncrypt"
      - "traefik.docker.network=traefik"

networks:
  traefik:
    external: true
